### ISSUE TITLE
Column alignment

### ISSUE THREAD

**Issue by mattjohnsonpint** [gilmoreorless/sublime-zoneinfo#1]
Thanks for this!

In addition to your syntax highlighting rules, I also find that if I up the tab size to 8, the majority of columns line up.  Compare this to the example screenshot in the readme:

![image](https://cloud.githubusercontent.com/assets/1396388/10954693/dbdb2556-8303-11e5-9739-66073bd67c6c.png)

Not all of them line up still of course.

![image](https://cloud.githubusercontent.com/assets/1396388/10954758/324c49ce-8304-11e5-98e9-efb7dcfaa3f6.png)

Any ideas about how to fix the alignment - perhaps in the package itself?

**Comment by gilmoreorless** [comment]
Oh good call, I feel silly for not considering the tab size previously. I'll investigate what's possible in the package to set alignment.

**Comment by gilmoreorless** [comment]
Turns out it was as simple as adding a default `zoneinfo.sublime-settings` file with the right indentation rules.

**Comment by mattjohnsonpint** [comment]
Thanks!
